version: '3.1'
services:
  mongo-container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: kotlin
      MONGO_INITDB_ROOT_PASSWORD: kotlin
    ports:
      - 27017:27017
    volumes:
      - /var/lib/docker/volumes/mongo-expenses-manager:/data/db
    command: mongod